version: 2.1

build:
  docker:
    -image: circleci/openjdk:11-browsers-legacy

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
